codecov:
  token: ${{secrets.CODECOV_TOKEN}}

coverage:
  precision: 2
  round: up
  range: "80...100"
  notify:
    wait_for_ci: no

  status:
    project:
      default:
        target: auto
        threshold: null
        base: auto
        branches: null
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        flags: null
        paths: null

    patch:
      default:
        target: auto
        base: auto
        threshold: 3%
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

    changes:
      default:
        target: auto
        base: auto
        branches: null
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        flags: null
        paths: null

comment:
  layout: "header, diff, changes, sunburst, suggestions, tree, uncovered"
  require_changes: false
  behavior: default