name: gm_driver_lite
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  dio: ^3.0.10
  intl: ^0.16.1
  provider: ^4.3.3
  get_it: ^5.0.6
  freezed_annotation: ^0.12.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  sentry_flutter: ^4.0.4
  dio_retry: ^0.1.9-beta

  # Util
  alice: ^0.1.9
  path_provider: ^1.6.27
  package_info: ^0.4.3+2

  # Native
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  device_info: ^1.0.0
  flutter_map: ^0.10.1+1
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14

  # UI
  material_design_icons_flutter: ^4.0.5855
  flutter_svg: ^0.19.1
  flash: ^1.3.1
  roundcheckbox: ^1.0.0+1
  flutter_spinkit: ^4.1.2+1
  dropdown_search: ^0.4.8
  bottom_bar_with_sheet: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Test
  bloc_test: ^7.1.0
  mockito: ^4.1.4

  # Linting
  effective_dart: ^1.3.0

  # Util
  dependency_validator: ^2.0.1

  # Code Generation
  build_runner: ^1.10.13
  freezed: ^0.12.7
  import_sorter: ^4.4.1
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

import_sorter:
  emojis: false
  comments: false
